import { NextResponse } from "next/server";
import type {
  SymptomAssessmentRequest,
  SymptomAssessmentResult,
} from "@/types/symptom-assessment";

/**
 * POST /api/symptom-assessment
 *
 * Currently returns a deterministic mock keyed off simple keyword matching
 * so the frontend has something real to render end-to-end. To go live:
 *
 *   1. Add OPENAI_API_KEY to your environment.
 *   2. Replace runMockAssessment() below with a call to the OpenAI API,
 *      prompting it to return JSON matching SymptomAssessmentResult exactly.
 *   3. Keep the emergency-keyword short-circuit (detectEmergencyKeywords) —
 *      red-flag symptoms should never depend solely on a model call; a
 *      hard-coded safety net belongs in front of any LLM here.
 *
 * Nothing in the frontend needs to change — it depends only on the
 * SymptomAssessmentResult contract.
 */

const EMERGENCY_KEYWORDS = [
  "chest pain",
  "can't breathe",
  "cannot breathe",
  "difficulty breathing",
  "severe bleeding",
  "unconscious",
  "stroke",
  "numb on one side",
  "slurred speech",
  "suicidal",
  "want to die",
  "seizure",
];

function detectEmergencyKeywords(text: string): boolean {
  const lower = text.toLowerCase();
  return EMERGENCY_KEYWORDS.some((kw) => lower.includes(kw));
}

const DISCLAIMER =
  "This assessment is generated by an AI system for informational and decision-support purposes only. It is not a medical diagnosis. Always consult a licensed clinician for medical advice, and seek emergency care immediately if symptoms are severe or worsening.";

function buildEmergencyResult(): SymptomAssessmentResult {
  return {
    id: crypto.randomUUID(),
    createdAt: new Date().toISOString(),
    riskLevel: "emergency",
    confidenceScore: 0.9,
    possibleConditions: [],
    nextSteps: [
      {
        label: "Seek emergency care immediately",
        detail: "Call your local emergency number or go to the nearest emergency room now.",
        urgent: true,
      },
    ],
    homeCareGuidance: [],
    doctorConsultationRecommended: true,
    emergencyWarning:
      "Your description includes symptoms that can indicate a medical emergency. Please call emergency services or go to the nearest emergency room right away. Do not wait for further guidance from this app.",
    disclaimer: DISCLAIMER,
  };
}

function runMockAssessment(input: SymptomAssessmentRequest): SymptomAssessmentResult {
  const text = input.freeTextSymptoms.toLowerCase();

  if (detectEmergencyKeywords(text)) {
    return buildEmergencyResult();
  }

  const hasFever = text.includes("fever");
  const hasCough = /cough/.test(text);
  const longDuration = /week|weeks/.test(text) || (input.patientContext.durationDescription ?? "").includes("week");

  if (hasCough && longDuration) {
    return {
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      riskLevel: "moderate",
      confidenceScore: 0.72,
      possibleConditions: [
        { name: "Post-viral cough", confidence: 0.45, description: "A lingering cough following a respiratory infection, common after colds or flu." },
        { name: "Bronchitis", confidence: 0.3, description: "Inflammation of the airways, often causing a persistent cough with mucus." },
        { name: "Allergic or asthmatic cough", confidence: 0.18, description: "Cough triggered by airway sensitivity or allergens." },
      ],
      nextSteps: [
        { label: "See a doctor within the next few days", detail: "A cough lasting more than 2 weeks warrants a clinical evaluation to rule out underlying causes.", urgent: false },
        { label: "Monitor for red flags", detail: "Seek urgent care if you develop blood in your cough, high fever, or breathlessness.", urgent: false },
      ],
      homeCareGuidance: [
        { title: "Stay hydrated", detail: "Warm fluids can help soothe throat irritation and thin mucus." },
        { title: "Use a humidifier", detail: "Moist air can ease airway irritation, especially at night." },
        { title: "Avoid irritants", detail: "Steer clear of smoke, strong fragrances, and other airway irritants while recovering." },
      ],
      doctorConsultationRecommended: true,
      disclaimer: DISCLAIMER,
    };
  }

  if (hasFever) {
    return {
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      riskLevel: "low",
      confidenceScore: 0.68,
      possibleConditions: [
        { name: "Viral infection", confidence: 0.64, description: "A common viral illness causing fever, headache, and fatigue." },
        { name: "Tension headache", confidence: 0.22, description: "Headache related to stress, dehydration, or muscle tension, sometimes alongside mild fever from another cause." },
        { name: "Sinus infection", confidence: 0.14, description: "Inflammation of the sinuses, which can cause facial pressure, headache, and low-grade fever." },
      ],
      nextSteps: [
        { label: "Rest and monitor", detail: "Track your temperature every few hours and note any new symptoms.", urgent: false },
        { label: "See a doctor if fever persists past 3 days", detail: "Or sooner if your fever exceeds 101°F (38.3°C) or you develop a rash, stiff neck, or confusion.", urgent: false },
      ],
      homeCareGuidance: [
        { title: "Hydration", detail: "Drink water, oral rehydration solution, or clear broths regularly." },
        { title: "Rest", detail: "Allow your body time to recover; avoid strenuous activity." },
        { title: "Steam inhalation", detail: "Can help relieve sinus pressure and congestion." },
        { title: "Salt water gargle", detail: "Helps soothe a sore or irritated throat." },
      ],
      doctorConsultationRecommended: false,
      disclaimer: DISCLAIMER,
    };
  }

  return {
    id: crypto.randomUUID(),
    createdAt: new Date().toISOString(),
    riskLevel: "low",
    confidenceScore: 0.55,
    possibleConditions: [
      { name: "Mild, non-specific symptoms", confidence: 0.5, description: "Symptoms consistent with minor, self-limiting conditions such as fatigue or mild irritation." },
    ],
    nextSteps: [
      { label: "Monitor symptoms over the next 24–48 hours", detail: "Note any changes in severity or new symptoms that develop.", urgent: false },
    ],
    homeCareGuidance: [
      { title: "Rest and hydration", detail: "Basic supportive care is often sufficient for mild, short-lived symptoms." },
    ],
    doctorConsultationRecommended: false,
    disclaimer: DISCLAIMER,
  };
}

export async function POST(request: Request) {
  let body: SymptomAssessmentRequest;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!body.freeTextSymptoms || typeof body.freeTextSymptoms !== "string") {
    return NextResponse.json(
      { error: "freeTextSymptoms is required" },
      { status: 400 }
    );
  }

  // Simulate model latency so the UI's "assessing" state has something real to show.
  await new Promise((resolve) => setTimeout(resolve, 1200));

  const result = runMockAssessment(body);
  return NextResponse.json(result);
}
